[package]
name = "authme"
version = "7.1.1"
description = "Simple cross-platform two-factor (2FA) authenticator app for desktop."
authors = ["Lőrik Levente"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2", features = ["tray-icon"] }
auto-launch = "0.6.0"
sysinfo = "0.37.2"
argon2 = "0.5"
rand_core = { version = "0.6", features = ["std"] }
magic-crypt = "4.0.1"
keyring = { version = "3.6.3", features = ["apple-native", "windows-native", "linux-native"] }
once_cell = "1.15.0"
tauri-plugin-single-instance = { version = "2" }
rand = "0.8.5"
google_authenticator_converter = { path = "crates/google_authenticator_converter" }
tauri-plugin-os = "2"
tauri-plugin-process = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-fs = "2"
tauri-plugin-updater = "2"
tauri-plugin-opener = "2"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort"   # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true        # Enables link to optimizations
opt-level = "s"   # Optimize for binary size

[workspace]
members = ["crates/*"]
