name: Publish GitHub Actions Artifacts Example

on:
    push:
        branches: [test]

jobs:
    archive-build-artifacts:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Install modules
              run: npm i

            - name: Run Build
              run: npm run build

            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: authme-latest-linux-x64
                  path: dist
