name: Release Artifacts
on:
    push:
        tags:
            - "*"
jobs:
    test-tauri:
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: macos-latest
                      NAME: macos
                    - os: ubuntu-latest
                      NAME: linux
                    - os: windows-latest
                      NAME: windows
        runs-on: ${{ matrix.os}}
        env:
            TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            GH_TOKEN: ${{ github.token }}
            APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
            APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
            KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
            APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
            APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
            APPLE_ID: ${{ secrets.APPLE_ID }}
            APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Rust setup
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: "./core -> target"

            - name: Install trusted-signing-cli
              if: matrix.NAME == 'windows'
              run: |
                  cargo install trusted-signing-cli

            - name: "Apple silicon target"
              if: runner.os == 'macOS'
              run: |
                  rustup target add aarch64-apple-darwin
                  rustup target add x86_64-apple-darwin

            - name: Install webkit2gtk (ubuntu only)
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

            - name: Install app dependencies and build it
              if: runner.os == 'Linux' || runner.os == 'Windows'
              run: npm ci && npm run build

            - name: Install app dependencies and build it
              if: runner.os == 'macOS'
              run: npm ci && npm run build -- --target universal-apple-darwin

            - name: Remove useless folders
              run: |
                  rm -rf core/target/release/build
                  rm -rf core/target/release/deps
                  rm -rf core/target/release/bundle/appimage/authme.AppDir
                  npm run rename
              shell: bash

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: authme-${{matrix.NAME}}-${{runner.arch}}
                  path: core/target/release

            - name: Run Upload To Release Action
              uses: levminer/upload-to-release@test
              if: startsWith(github.event.ref, 'refs/tags/')
              id: upload
              with:
                  windows-files: "./core/target/release/upload/authme-%v-windows-x64.msi, ./core/target/release/upload/authme-%v-windows-x64.zip"
                  macos-files: "./core/target/release/upload/authme-%v-macos-universal.dmg"
                  linux-files: "./core/target/release/upload/authme-%v-linux-x64.appimage, ./core/target/release/upload/authme-%v-linux-x64.deb"

            - name: Hash
              if: runner.os == 'Windows'
              run: cat ./core/target/release/upload/authme-${{steps.upload.outputs.version}}-${{matrix.NAME}}-x64.sig
              shell: bash
